apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:w9/hbLkBSilFUpdBjOgd9hxCBMRr3N9yf71crw==,iv:WuHgHGp0iQJCm79JNjkptfyWwA1jODNNnRxGlcw1Dmk=,tag:1eKEKNpZHWvF1sqLCTCbAg==,type:str]
    admin-user: ENC[AES256_GCM,data:22/CHUgI/BI=,iv:2xoKq07sy152XDWxvPqjzpfS9pcfr/SfAlsg4yT6Ot0=,tag:yaNYbbb4RsxJq4x8pc3l1Q==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOEF1UFZGSHhsMEcySnUz
            a0dwZlVod3JXdm01blFzaUtNbG5TbjJOTFVZCm5zRVlDRjVuRXIraDFxdTNqc2Nn
            Y1V3K1RNVU54b3krRjZmMjBtcUR2c2sKLS0tIHNncmJOOGVud3ppMEtYdndMVE9K
            Vjd4eTlmM2xTa3NpeU00S1VOV01XRE0KW05rONvhz7d+7iVSL+ZrOgGh0MTSmW8Y
            3PSEJNgYcb8yYKqGH3f4BItJH7kUmfZjAcdatChk104HFny3Cey15Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1040x4w5m3ryxje562h54szm835kmp6nff93467fx43dlhu3zrawqv89cc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T16:40:29Z"
    mac: ENC[AES256_GCM,data:f4bKL2XkYdx5oUUr6C9VN+Oj9CEyvTtaxN4+zLfQ3p21Csh8rsJ09mn+Bmgdnog2VdHg++OLGuDVRq3MCgGszV/1Cpe3SK2bEH60U5GirN2V3QvtXteIevv62KXur2MYfIxtlrKVSa8S8hxzYnm1Cct2s8LUifXwXtEuhK3D1y0=,iv:oA5tSbD4+5iEcqZmOki2F0PlBxB/GqEkxQEFCiXIfAE=,tag:WE8zT6rou5Y8KYGSHKHarg==,type:str]
    version: 3.13.3
