apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# no namespace: here - the issuers are cluster-wide and the rest lives in kube-system
resources:
  - clusterissuer-staging.yaml
  - clusterissuer-prod.yaml
  - lab-wildcard-certificate.yaml
  - traefik-default-tlsstore.yaml
