apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:4q9D/LU5m3jasXzKxhe7HNG0WZVLW9kFgf0PbiBZNUvql6vZmzSmB0iI5felQPXN5qLjtE+MO4cIhg+kMTDPtzkqqeOQVE6Zbi3hFLVzGBiru5LdSmHfEqKqjIxK37e/+RIC8YtU+C9hyKB6PGbzuXe2ahN+DqrhMq6yNbG93eSYxHgrhEv1aQaIHgnzzesSM7Ffm8Ct42vj0hId3TSFy9WqW1H4i25BkoiYxYj+OOCk7jTVF5A410MgzOYmbIg7rf0qv2S21jbAvIYEJaUc77g7TFj16iTsDQpwerg2IMad2mUaKR3wZgUYhTM=,iv:5uwi0uUNpAPTjChuUrNjz9+yyM5qXU4RLF7MErj+VhE=,tag:MGsstJEEXFYHa8knzRRCvQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzODFhOFNUQVNSbHFKSlFQ
            bmYwK1Z4QVFUaWpmK3U2aDdoK283NVMwMHp3Cko3c2xYL2RWRDhKYjJiWWMzcXJX
            QmdjNzVqTGJLSUlNS3RES0lHTXgyTmMKLS0tIEtpWXU3NHU4azBna3ltREdUdFZB
            M3RtOEVpdGFOdXZGOTJMMTRzdmNRQWsK76u7dRCF2Emd2ee7Ic4M0h5NwC98KsJi
            lc5muZbN7aq6wGHkkJIGCaIwtwm3C2rWAJVJGvu3tC3L83EQk01Ptw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1040x4w5m3ryxje562h54szm835kmp6nff93467fx43dlhu3zrawqv89cc3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T10:16:43Z"
    mac: ENC[AES256_GCM,data:Con0exulAghhqaPXEZbEeyu+OOyIVA1HYB5hMOsG8ODNcPeA+7w/IlzqXVF5KjMDKOPaGKpT74YMMqZdTmKty7N8jtvG5hralya+EhEvgTys7ffV9faowqpBqe2l+Eo5o4RKiU9dBygSZJmR14NRzk7Xs7NyFGsF1DdWszmq0gM=,iv:e8WT8Haz3ZQZlknDzYVOEh+LyHO0nEEOAWuImvr/xio=,tag:PQ0ELVyWfggj56spYSx1rw==,type:str]
    version: 3.13.3
